# Generated by Django 5.2.13 on 2026-04-17 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nfc", "0001_initial"),
        ("part", "0147_remove_part_default_supplier"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="nfctaglink",
            options={"ordering": ["-linked_at"]},
        ),
        migrations.AddField(
            model_name="nfctaglink",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="nfctaglink",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="nfctaglink",
            name="part",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nfc_tags",
                to="part.part",
                verbose_name="Linked Part",
            ),
        ),
        migrations.AlterField(
            model_name="nfctaglink",
            name="uid",
            field=models.CharField(
                max_length=64, unique=True, verbose_name="NFC Tag UID"
            ),
        ),
    ]
