# Generated by Django 5.2.13 on 2026-05-11 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nfc", "0002_alter_nfctaglink_options_nfctaglink_active_and_more"),
        ("part", "0147_remove_part_default_supplier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nfctaglink",
            name="part",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nfc_tag",
                to="part.part",
                unique=True,
                verbose_name="Linked Part",
            ),
        ),
    ]
