# Generated by Django 5.2.13 on 2026-05-12 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nfc", "0003_alter_nfctaglink_part"),
        ("part", "0147_remove_part_default_supplier"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="nfctaglink",
            name="part",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nfc_tag",
                to="part.part",
                verbose_name="Linked Part",
            ),
        ),
        migrations.AlterField(
            model_name="nfctaglink",
            name="uid",
            field=models.CharField(max_length=64, verbose_name="NFC Tag UID"),
        ),
        migrations.AddConstraint(
            model_name="nfctaglink",
            constraint=models.UniqueConstraint(
                condition=models.Q(("active", True)),
                fields=("uid",),
                name="unique_active_uid",
            ),
        ),
        migrations.AddConstraint(
            model_name="nfctaglink",
            constraint=models.UniqueConstraint(
                condition=models.Q(("active", True)),
                fields=("part",),
                name="unique_active_part",
            ),
        ),
    ]
